<?php

namespace App\Livewire\Agents;

use App\Models\AgentDeployment;
use App\Services\Governance\ScorecardService;
use Illuminate\Support\Facades\Cache;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Lazy;
use Livewire\Component;

#[Lazy]
class ScorecardViewer extends Component
{
    public int $deploymentId;

    public string $period = '30d';

    public function mount(int $deploymentId): void
    {
        $this->deploymentId = $deploymentId;
    }

    #[Computed]
    public function deployment(): AgentDeployment
    {
        // Cache deployment with agent relation for 5 min — avoids repeated joins
        return Cache::remember("scorecard_deployment_{$this->deploymentId}", 300, fn () => AgentDeployment::with(['agent.agentDepartment', 'scorecards' => fn ($q) => $q->latest()->limit(6)])
            ->findOrFail($this->deploymentId)
        );
    }

    #[Computed]
    public function scorecard()
    {
        return $this->deployment->latestScorecard;
    }

    #[Computed]
    public function history()
    {
        // Cache scorecard history for 5 min — generated by background job, not real-time
        return Cache::remember("scorecard_history_{$this->deploymentId}", 300, fn () => $this->deployment->scorecards()->latest()->limit(6)->get()
        );
    }

    public function recalculate(): void
    {
        $period = match ($this->period) {
            '7d' => 'weekly',
            '90d' => 'quarterly',
            default => 'monthly',
        };

        app(ScorecardService::class)->calculatePeriodScorecard($this->deployment, $period);

        // Invalidate caches after recalculation
        Cache::forget("scorecard_deployment_{$this->deploymentId}");
        Cache::forget("scorecard_history_{$this->deploymentId}");
        unset($this->deployment, $this->scorecard, $this->history);

        session()->flash('status', 'Scorecard recalculated.');
    }

    public function render()
    {
        return view('livewire.agents.scorecard-viewer');
    }
}
